// Print an imageMeta record for every file in public/images/projects.
// Run after adding/replacing a screenshot, then paste into src/data/imageMeta.ts.
//   node scripts/measure-images.mjs
// Honors EXIF orientation (portrait iPhone photos report rotated dimensions)
// and warns when a file's real format does not match its extension.
import sharp from 'sharp';
import { readdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join, basename, extname } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const dir = join(__dirname, '..', 'public', 'images', 'projects');

const files = (await readdir(dir)).filter(f => /\.(jpe?g|png|webp)$/i.test(f));
console.log('// generated by scripts/measure-images.mjs');
for (const f of files.sort()) {
  const id = basename(f, extname(f));
  const meta = await sharp(join(dir, f)).metadata();
  let { width, height } = meta;
  const { orientation, format } = meta;
  if (orientation >= 5) [width, height] = [height, width]; // EXIF 5-8 = 90° rotations
  const ext = extname(f).slice(1).toLowerCase();
  const declared = ext === 'jpg' ? 'jpeg' : ext;
  if (format !== declared) {
    console.log(`  // WARNING: ${f} is actually ${format}, not .${ext}`);
  }
  const ratio = (width / height).toFixed(2);
  const key = /[^a-z0-9]/i.test(id) ? `'${id}'` : id;
  console.log(`  ${key}: { width: ${width}, height: ${height} }, // ${ratio}`);
}
