// Print an imageMeta record for every file in public/images/projects.
// Run after adding/replacing a screenshot, then paste into src/data/imageMeta.ts.
//   node scripts/measure-images.mjs
import sharp from 'sharp';
import { readdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join, basename, extname } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const dir = join(__dirname, '..', 'public', 'images', 'projects');

const files = (await readdir(dir)).filter(f => /\.(jpe?g|png|webp)$/i.test(f));
console.log('// generated by scripts/measure-images.mjs');
for (const f of files.sort()) {
  const id = basename(f, extname(f));
  const { width, height } = await sharp(join(dir, f)).metadata();
  const ratio = (width / height).toFixed(2);
  const fit = ratio < 1.4 ? 'contain' : 'cover'; // tall figures mount; wide app shots fill
  const key = /[^a-z0-9]/i.test(id) ? `'${id}'` : id;
  console.log(`  ${key}: { width: ${width}, height: ${height}, fit: '${fit}' }, // ${ratio}`);
}
